dubium/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from modusuario import views
#from modreserva import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('modusuario.urls')),
    url(r'^recurso/', include('modrecurso.urls')),
    url(r'^mantenimiento/', include('modmantenimiento.urls')),
    url(r'^reserva/', include('modreserva.urls')),
    url(r'^publico/', include('modpublico.urls')),
]

modreserva/urls.py
from django.conf.urls import url
from . import views

app_name = 'modreserva'

urlpatterns = [
    #url(r'^elegir/$', views.elegir_reserva, name='elegir_reserva'),
    # crear reserva
    url(r'^crear/$', views.crear_reserva, name='crear_reserva'),
    # lista de mantenimientos
    url(r'^listar/$', views.reserva_list, name='reserva_lista'),
    url(r'^listar/reporte_reserva_pdf/$',views.ReporteReservasPDF.as_view(), name='reporte_reserva_pdf'),
    # eliminar mantenimientos
    url(r'^eliminar-(?P<parameter>[\w-]+).html', views.eliminar_reserva, name='eliminar_reserva'),
    # url(r'^mantenimiento/$', views.mantenimiento_list),
    # crear reserva anticipada
    url(r'^crearA/$', views.crear_reserva_ant, name='crear_reserva_ant'),
    # resolver reservas anticipadas
    url(r'^resolver/$', views.reserva_list_resolver, name='reserva_list_resolver'),
    # entrega-devolucion de recursos de reservas
    url(r'^entregar-(?P<parameter>[\w-]+).html', views.entrega_recurso, name='entrega_recurso'),
    #cancelar reservas
    url(r'^cancelar-(?P<parameter>[\w-]+).html', views.cancelar_reserva, name='cancelar_reserva'),
    #vista previa de la resolucion de reservas
    #url(r'^preview/$', views.vista_previa, name='vista_previa'),
    url(r'^modificar-(?P<parameter>[\w-]+).html', views.modificar_reserva, name='modificar_reserva'),
    # crear reserva
    url(r'^crearH/$', views.crear_historial, name='crear_historial'),
    #buscar recurso
    url(r'^buscar_recurso_list/$', views.buscar_recurso_lista, name='buscar_recurso_list'),
    # editar datos de reserva
    url(r'^recuperar-(?P<parameter>[\w-]+).html', views.recuperar, name='recuperar'),
]

modusuario/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'modusuario'

urlpatterns = [
    # previous login view
    # url(r'^login/$', views.user_login, name='login'),

    # login / logout urls
    url(r'^login/$', auth_views.login,  name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),

    # dashboard
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # dashboard
    url(r'^$', views.home, name='home'),

    # change password urls
    url(r'^password-change/$', auth_views.password_change, {'post_change_redirect': 'modusuario:password_change_done'}, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),

    # restore password urls
    url(r'^password-reset/$', auth_views.password_reset, {'post_reset_redirect': 'modusuario:password_reset_done'}, name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, {'post_reset_redirect': 'modusuario:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # register user
    url(r'^register/$', views.user_register, name='register'),

    # edit user propio
    url(r'^edit/$', views.user_detail_edit, name='edit'),

    # edit parameters
    url(r'^parameters/$', views.email_config_edit, name='configuracion'),

    # user list
    #url(r'^usuario/list/$', views.UserList.as_view(), name='listar_usuarios'),
    url(r'^usuario/list/$', views.user_list, name='listar_usuarios'),
    # user detail
    url(r'^usuario/(?P<pk>\d+)/$', views.UserDetail.as_view(), name='detalle_usuario'),
    # user create
    url(r'^usuario/create/$', views.user_create, name='crear_usuario'),
    # user update
    url(r'^usuario/(?P<pk>\d+)/update/$', views.user_update, name='actualizar_usuario'),
    # user delete
    url(r'^usuario/(?P<pk>\d+)/delete/$', views.UserDelete.as_view(), name='eliminar_usuario'),

    # area list
    url(r'^area/list/$', views.AreaList.as_view(), name='area_list'),
    # area create
    url(r'^area/create/$', views.AreaCreate.as_view(), name='area_create'),
    # area update
    url(r'^area/(?P<pk>\d+)/update/$', views.AreaUpdate.as_view(), name='area_update'),
    # area delete
    url(r'^area/(?P<pk>\d+)/delete/$', views.AreaDelete.as_view(), name='area_delete'),

    # rol list
    url(r'^rol/list/$', views.RolList.as_view(), name='rol_list'),
    # rol create
    url(r'^rol/create/$', views.RolCreate.as_view(), name='rol_create'),
    # rol update
    url(r'^rol/(?P<pk>\d+)/update/$', views.RolUpdate.as_view(), name='rol_update'),
    # rol delete
    url(r'^rol/(?P<pk>\d+)/delete/$', views.RolDelete.as_view(), name='rol_delete'),
]

modreserva/models.py
from django.db import models
from django.contrib.admin.widgets import AdminDateWidget
from modusuario.models import Profile
from django.contrib.auth.models import User
from modrecurso.models import TipoRecurso,Recurso
from django.utils import timezone
from django.conf import settings
from datetime import datetime,date,time,timedelta
from modmantenimiento.tasks import set_recurso_as_active

class Reserva(models.Model):
    """
        Modelo utilizado para la creacion de reserva de recursos.
    """
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True)
    fecha_reserva = models.DateField(blank=True, default=date.today)
    dias=models.IntegerField(blank=True,default=1)
    tipo_recurso = models.ForeignKey('modrecurso.TipoRecurso', null=False)
    recurso = models.ForeignKey('modrecurso.Recurso',blank=True,null=True)
    hora_inicio=models.TimeField(blank=True, null=True)
    hora_final=models.TimeField(blank=True,default='00:00')
    DIRECTA = 'DIRECTA'
    ANTICIPADA = 'ANTICIPADA'
    TIPO_CHOICES = (
        (DIRECTA, 'Directa'),
        (ANTICIPADA, 'Anticipada'),
    )
    tipo = models.CharField(
             max_length=12,
             choices=TIPO_CHOICES,
             blank=True,
             null=True,
         )
    #descripcion = models.CharField(max_length=100, null=True, blank=True)
    ACEPTADA = 'ACEPTADA'
    RECHAZADA = 'RECHAZADA'
    CANCELADA = 'CANCELADA'
    FINALIZADA = 'FINALIZADA'
    EN_ESPERA = 'EN ESPERA'
    EN_CURSO = 'EN CURSO'
    ESTADO_CHOICES = (
        (ACEPTADA, 'Aceptada'),
        (RECHAZADA, 'Rechazada'),
        (CANCELADA, 'Cancelada'),
        (FINALIZADA, 'Finalizada'),
        (EN_ESPERA, 'En Espera'),
        (EN_CURSO, 'En Curso')
    )
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, blank=True,null=True)
    fecha_hora_entrega=models.DateTimeField(blank=True,null=True)
    fecha_hora_devolucion = models.DateTimeField(blank=True, null=True)
    fecha=models.DateTimeField(auto_now_add=True, blank=False)
    class Meta:
        permissions = (
            ("list_all_reserva", "Can list all reserva"),
            ("list_reserva", "Can list certain reserva"),
            ("entrega_recurso", "Can manage recurso"),
            ("cancelar_reserva", "Can cancel reserva"),
        )

    def __str__(self):
        return str(self.id)
        #return 'Reserva del recurso {}'.format(self.recurso)
    def save(self, *args, **kwargs):

        create_task = False  # variable to know if celery task is to be created
        if self.pk is None:  # Check if instance has 'pk' attribute set
            # Celery Task is to created in case of 'INSERT'
            create_task = True  # set the variable

        super(Reserva, self).save(*args, **kwargs)  # Call the Django's "real" save() method.
        if create_task and self.recurso!=None:  # check if task is to be created
            # pass the current instance as 'args' and call the task with 'eta' argument
            # to execute after the race `end_time`

            #print(datetime.combine(self.fecha_reserva,self.hora_inicio))
            print(self.fecha_reserva)
            print(self.hora_inicio)
            print(self.fecha)

            set_recurso_as_active.apply_async(args=[self.recurso.id],
                                             eta=(datetime.combine(self.fecha_reserva,self.hora_inicio))+timedelta(hours=4))  # task will be executed after 'race_end_time'

class Historial(models.Model):
     usuario=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True, related_name='usuario')
     usuario_dev=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True, related_name='usuario_dev')
     recurso = models.ForeignKey('modrecurso.Recurso',null=True,blank=True)
     reserva=models.ForeignKey('modreserva.Reserva',null=True,blank=True)
     descripcion=models.CharField(max_length=100,null=True,blank=True,default="Se presento el recurso tal y cual como se retiro")
     DISPONIBLE = 'DISPONIBLE'
     DESCOMPUESTO = 'DESCOMPUESTO'
     ESTADO_CHOICES = (
         (DISPONIBLE, 'Disponible'),
         (DESCOMPUESTO, 'Descompuesto'),
     )
     estado = models.CharField(max_length=16, choices=ESTADO_CHOICES, blank=True, default='DISPONIBLE')

     def __str__(self):
         return self.descripcion

modreserva/templates/modreserva/base_modreserva.html
{% extends "base.html" %}

{% block title %}Modulo de Reservas{% endblock %}


{% block dropdown-title %}{% endblock %}

{% block dropdown-menu %}
{% endblock %}

{% block content %}
{% endblock %}

modreserva/templates/modreserva/crear_historial.html
{% extends "modreserva/base_modreserva.html" %}



{% block title %}Reporte{% endblock %}
{% block extrahead %}
    {{ form.media }}
    {{ form1.media }}
{% endblock %}
{% block content %}
    {% if perms.modreserva.add_reserva %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Nuevo Reporte</h1><hr>
              <h2> {{ request.user.first_name }}</h2>
              <p>Ingresa los siguientes datos: </p><br>
              <form ation="." method="post">
                  {% csrf_token %}
                  {{ form1.as_p }}
                  {{ form.as_p }}
                  <div class="modal-footer" style="text-align:left">
                      <a href="{% url 'modreserva:reserva_lista' %}" class="btn btn-primary" role="button">Cancelar </a>
                      <button type="submit" class="btn btn-primary">Crear</button>
                  </div>
              </form>
          </div>
        </div>
    {% else %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Permiso denegado! </h1><br>
              <p> Usted no posee permiso para crear historial </p><br>
          </div>
        </div>
    {% endif %}
{% endblock content %}

modreserva/templates/modreserva/crear_reserva.html
{% extends "modreserva/base_modreserva.html" %}



{% block title %}Crear Reserva Directa{% endblock %}
{% block extrahead %}
    {{ form.media }}
{% endblock %}
{% block content %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Nueva Reserva Directa</h1><hr>
              <h2> {{ request.user.first_name }}</h2>
              <p>Ingresa los siguientes datos: </p>
              <form action="." method="post">
                  {% csrf_token %}
                  <h3>Recurso:<a title=" Haga click para seleccionar un recurso" href="{% url 'modreserva:buscar_recurso_list' %}"><div class="form-control" >{{recurso.nombre}}</div></a></h3>{#                  <h5 class="hidden"> {{ form.recurso}} </h5>#}
{#                  <h5 class="hidden"> {{ form.recurso}} </h5>#}
{#                  <h3>Tipo de Recurso: {{ form.tipo_recurso}}</h3>#}
{#                  <h3>Hora de Inicio: {{ form.hora_inicio}}</h3>#}
{#                  <h3>Hora de Fin: {{ form.hora_final}}</h3>#}
                  {{ form.as_p }}
                  <div class="modal-footer" style="text-align:left">
                      <a href="{% url 'modreserva:reserva_lista' %}" class="btn btn-primary" role="button">Cancelar </a>
                      <button type="submit" class="btn btn-primary">Crear</button>
                  </div>
              </form>
          </div>
        </div>
{% endblock content %}

modreserva/templates/modreserva/crear_reserva_ant.html
{% extends "modreserva/base_modreserva.html" %}



{% block title %}Crear Reserva Anticipada{% endblock %}
{% block extrahead %}
    {{ form.media }}
{% endblock %}
{% block content %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Nueva Reserva Anticipada</h1><hr>
              <h2> {{ request.user.first_name }}</h2>
              <p>Ingresa los siguientes datos: </p>
              <form action="." method="post">
                  {% csrf_token %}
                    <h3>Recurso:<a title=" Haga click para seleccionar un recurso" href="{% url 'modreserva:buscar_recurso_list' %}"><div class="form-control" >{{recurso.nombre}}</div></a></h3>
{#                    <h5 class="hidden"> {{ form.recurso}} </h5>#}
{#                    <h3>Tipo de Recurso: {{ form.tipo_recurso}}</h3>#}
{#                    <h3>Hora de Inicio: {{ form.hora_inicio}}</h3>#}
{#                    <h3>Hora de Fin: {{ form.hora_final}}</h3>#}
{#                    <h3>Fecha de Reserva: {{ form.fecha_reserva}}</h3>#}
{#                    <h3>Dias a ser reservados: {{ form.dias}}</h3>#}
                    {{ form.as_p }}
                  <div class="modal-footer" style="text-align:left">
                      <a href="{% url 'modreserva:reserva_lista' %}" class="btn btn-primary" role="button">Cancelar </a>
                      <button type="submit" class="btn btn-primary">Crear</button>
                  </div>
              </form>
          </div>
        </div>
{% endblock content %}

modreserva/templates/modreserva/eliminar_reserva.html
{% extends "modreserva/base_modreserva.html" %}

{% block title %}Reserva eliminada{% endblock %}

{% block content %}
    {% if perms.modreserva.delete_reserva %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Reserva eliminada </h1><hr>
              <p>Su reserva ha sido eliminado exitosamente. Ahora puedes <a href="{% url "modreserva:reserva_lista" %}">volver</a></p><br>
          </div>
        </div>
    {% else %}
        <p></p>
        <div class="container" >
          <div class="jumbotron">
              <h1> Permiso denegado! </h1><hr>
              <p>No posee permiso para eliminar la reserva.<br>
          </div>
        </div>
    {% endif %}
{% endblock content %}

modreserva/templates/modreserva/historial_agregado.html
{% extends "modreserva/base_modreserva.html" %}

{% block title %}Reserva Creada{% endblock %}

{% block content %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Reporte Agregado </h1><hr>
              <p>Su reporte ha sido agregado exitosamente. Ahora puedes <a href="{% url "modreserva:reserva_lista" %}">volver</a></p><br>
          </div>
        </div>
{% endblock content %}

modreserva/templates/modreserva/modificar_reserva.html
{% extends "modreserva/base_modreserva.html" %}



{% block title %}Modificar reserva{% endblock %}
{% block extrahead %}
    {{ form.media }}
{% endblock %}
{% block content %}
    {% if perms.modreserva.add_reserva %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Modificar Reserva</h1><hr>
              <h2> {{ request.user.first_name }}</h2>
              <p>Ingresa los siguientes datos: </p>
              <form action="#" method="post">
                  {% csrf_token %}
                  <h3>Usuario: {{ form.usuario }}</h3>
                  <h3>Tipo de Recurso {{ form.tipo_recurso }}</h3>
                  <h3>Recurso: <a title=" Haga click para seleccionar un recurso" href="{% url 'modreserva:buscar_recurso_list' %}"><div class="form-control" >{{recurso.nombre}}</div></a></h3>
                  <h5 class="hidden"> {{ form.recurso }}</h5>
                  <h3>Estado: {{ form.estado }}</h3>

                  <div class="modal-footer" style="text-align:left">
                      <a href="{% url 'modreserva:reserva_list_resolver' %}" class="btn btn-primary" role="button">Cancelar </a>
                      <button type="submit" class="btn btn-primary">Crear</button>
                  </div>
              </form>
          </div>
        </div>
    {% else %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Permiso denegado! </h1><br>
              <p> Usted no posee permiso para modificar reserva </p><br>
          </div>
        </div>
    {% endif %}
{% endblock content %}

modreserva/templates/modreserva/reserva_creado.html
{% extends "modreserva/base_modreserva.html" %}

{% block title %}Reserva Creada{% endblock %}

{% block content %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Reserva Creada </h1><hr>
              <p>Su reserva ha sido creado exitosamente. Ahora puedes <a href="{% url "modreserva:reserva_lista" %}">volver</a></p><br>
          </div>
        </div>
{% endblock content %}

modreserva/templates/modreserva/reserva_filtros.html
{% block extrahead %}
    {{ form.media }}
{% endblock %}
<span id="span_filtros" style="background-color: #66afe9"><strong>Filtros</strong></span>
    <div id="filtros" style="background-color: #2aabd2" hidden="hidden">
   <form action="." method="get">
        {{ form.as_p }}
        <input type="submit" value="Filtrar" id="btnFiltrar">
   </form>
</div>

<script>
    $(document).ready(function() {
        var bandera = true;
        $("#span_filtros").click(function() {
            if(bandera){
                $("#filtros").slideDown();
                bandera = false;
            }else{
                $("#filtros").slideUp();
                bandera = true;
            }
        });
    });
</script>

modreserva/templates/modreserva/reserva_lista.html
{% extends 'modreserva/base_modreserva.html' %}
{% load static %}
{% block title %}Reserva{% endblock %}
{% block extrahead %}
    {{ form.media }}
    {{ form1.media }}
{% endblock %}
{% block content %}

    <div class="container" >
      <div class="jumbotron">
        <h1>Reservas</h1><hr>
         <!--<input type="text" id="myInput" class="myInput" onkeyup="buscar()" placeholder="Ingrese el usuario que desea buscar.">-->
         <!-- BUSCAAAR-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="input-group" id="adv-search">
                            <input type="text" class="form-control" id="myInput" onkeyup="buscar()" placeholder="Ingrese el nombre del Recurso">
                            <div class="input-group-btn">
                                <div class="btn-group" role="group" >
                                    <div class="dropdown dropdown-lg">
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="height: 45px;width: 45px"><img src="{% static 'img/filtro.png' %}" width="19" height="19"></button>
                                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                                            <form class="form-horizontal" action="." method="get" role="form">
{#                                                {% include 'modreserva/reserva_filtros.html' %}#}
                                                {{ form.as_p }}
                                                <button type="submit" class="btn btn-sm btn-primary" id="btnFiltrar">Filtrar</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
           <!-- BUSCAAAR-->
            <br>
{#        <table id="myTable" class="header" cellspacing="0" width="100%">#}
          <table id="myTable" class="tablesorter" cellspacing="0" width="100%">
            <thead class="table">
                <tr>
                    <th>Usuario</th>
                    <th>Tipo de Recurso </th>
                    <th>Recurso</th>
                    <th>Rango Horario</th>
                <!--<th>Final</th>-->
                    <th>Tipo</th>
                    <!--<<th>Descripcion</th>-->
                    <th>Estado</th>
                    <th>Fecha</th>
                    <th>Fecha Reserva</th>
                    <th>Detalles</th>

                    {% if perms.modreserva.entrega_recurso or perms.modreserva.cancelar_reserva %}
                        <th>Alterar</th>
                    {% endif %}
                    {% if perms.modreserva.delete_reserva %}
                        <th>Eliminar</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for Reserva in reservas %}
                    <tr>
                        <td>{{ Reserva.usuario }}</td>
                        <td>{{ Reserva.tipo_recurso }}</td>
                        <td>{{ Reserva.recurso }}</td>
                        <td>{{ Reserva.hora_inicio }}-{{ Reserva.hora_final }}</td>
                        <td>{{ Reserva.tipo }}</td>
                        <td>{{ Reserva.estado }}</td>
                        <td>{{ Reserva.fecha }}</td>
                        <td>{{ Reserva.fecha_reserva }}</td>
                        <td>
                            <img src="{% static 'img/detalles2.png' %}" width="25" height="25" alt="more" style="cursor: pointer;" data-toggle="modal" data-target="#myModal{{ forloop.counter }}">
                            <!-- Modal -->
                            <div class="modal fade" id="myModal{{ forloop.counter }}" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h3 class="modal-title"> Detalles de la Reserva</h3>
                                        </div>
                                        <div class="modal-body">
                                           <h4>Hora de Entrega</h4>
                                           {{ Reserva.fecha_hora_entrega }}
                                           <h4>Hora de Devolución</h4>
                                           {{ Reserva.fecha_hora_devolucion }}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>&nbsp
                                            <a href="{% url "modreserva:recuperar" parameter=Reserva %}"><button type="button" class="btn btn-default">Añadir</button></a>
{#                                            <a href="{% url "modreserva:recuperar" parameter=Reserva %}"><img src="{% static 'img/añadir2.png' %}" width="25" height="25" alt="añadir2"/></a>#}
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </td>

                        <td>
                            {% if perms.modreserva.entrega_recurso %}
                             <a href="{% url "modreserva:entrega_recurso" parameter=Reserva.id %}"><img src="{% static 'img/check2.png' %}" width="25" height="25" alt="more"/></a>
                            {% endif %}
{#                            {% if perms.modreserva.cancelar_reserva %}#}
                                <a href="{% url "modreserva:cancelar_reserva" parameter=Reserva.id %}"><img src="{% static 'img/cancelar2.png' %}" width="26" height="26" alt="eliminar1"/></a>
{#                            {% endif %}#}
                        </td>
                        <td>
                            {% if perms.modreserva.delete_reserva %}
                                <a href="{% url "modreserva:eliminar_reserva" parameter=Reserva.id %}"><img src="{% static 'img/eliminar1.png' %}" width="25" height="25" alt="eliminar1"/></a>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                  <h3>No hay reservas</h3>
                {% endfor %}
            </tbody>
          </table>
            {% if reservas.has_other_pages %}
                <ul class="pagination">
                    {% if reservas.has_previous %}
                        {# No me pregunten como, pero toda esa parte del codigo a partir del "for key...." es para que no se pierdan los parametros al cambiar de pagina #}
                        <li><a href="?page={{ reservas.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in reservas.paginator.page_range %}
                        {% if reservas.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if reservas.has_next %}
                            <li><a href="?page={{ reservas.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&raquo;</a></li>
                    {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
            <br><br>
                <a class="btn btn-sm btn-primary" href="{% url "modusuario:home" %}" role="button">&laquo; Atrás </a>
            &nbsp &nbsp
{#            {% if perms.modreserva.add_reserva %}#}
                <a class="btn btn-sm btn-primary" href="{% url "modreserva:crear_reserva" %}" role="button">Crear Directa</a>&nbsp &nbsp
                <a class="btn btn-sm btn-primary" href="{% url "modreserva:crear_reserva_ant" %}" role="button">Crear Aniticipada</a>&nbsp &nbsp
{#            {% endif %}#}
            {% if perms.modreserva.entrega_recurso %}
                <a class="btn btn-sm btn-primary" href="{% url "modreserva:reserva_list_resolver" %}" role="button">Resolver Reservas</a>&nbsp &nbsp
            {% endif %}
                <div class="btn-group dropup" role="group">
                    <div class="dropdown dropdown-lg" >
                       <button style="border-radius:4px;" type="button" class="btn btn-sm btn-primary dropdown-toggle"  data-toggle="dropdown" aria-expanded="false" >Reporte</button>
                          <div class="dropdown-menu dropdown-menu" role="menu">
                              <form class="form-horizontal" action="{% url "modreserva:reporte_reserva_pdf" %}" method="get" role="form">
                                {{ form1.as_p }}
                                <button type="submit" class="btn btn-sm btn-primary" id="btnGenerar" style="border-radius:5px;">Generar PDF</button>
                             </form>
                          </div>
                    </div>
                </div>

      </div>
    </div> <!-- /container -->

    <script>
    function buscar()
    {
        var input, filter, table, tr, td, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[2];
            if (td)
            {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1)
                {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
    $(document).ready(function()
    {
        $("#myTable").tablesorter();
    }
    );


    </script>


{% endblock content %}