dubium/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from modusuario import views
#from modreserva import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('modusuario.urls')),
    url(r'^recurso/', include('modrecurso.urls')),
    url(r'^mantenimiento/', include('modmantenimiento.urls')),
    url(r'^reserva/', include('modreserva.urls')),
    url(r'^publico/', include('modpublico.urls')),
]

modmantenimiento/urls.py
from django.conf.urls import url
from . import views

app_name = 'modmantenimiento'

urlpatterns = [
    # crear mantenimiento preventivo
    url(r'^crear_preventivo/$', views.crear_mantenimiento_preventivo, name='crear_mantenimiento_preventivo'),
    # crear mantenimiento correctivo
    url(r'^crear_correctivo/$', views.crear_mantenimiento_correctivo, name='crear_mantenimiento_correctivo'),
    # modificar mantenimiento
    url(r'^modificar-(?P<parameter>\d+)/', views.modificar_mantenimiento, name='modificar_mantenimiento'),
    # lista de mantenimientos
    url(r'^listar/$', views.mantenimiento_list, name='mantenimiento_lista'),
    # eliminar mantenimientos
    url(r'^eliminar-(?P<parameter>[\w-]+).html', views.eliminar_mantenimiento, name='eliminar_mantenimiento'),

    url(r'^buscar_recurso/$', views.buscar_recurso_lista, name='buscar_recurso_lista'),
]

modusuario/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'modusuario'

urlpatterns = [
    # previous login view
    # url(r'^login/$', views.user_login, name='login'),

    # login / logout urls
    url(r'^login/$', auth_views.login,  name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),

    # dashboard
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # dashboard
    url(r'^$', views.home, name='home'),

    # change password urls
    url(r'^password-change/$', auth_views.password_change, {'post_change_redirect': 'modusuario:password_change_done'}, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),

    # restore password urls
    url(r'^password-reset/$', auth_views.password_reset, {'post_reset_redirect': 'modusuario:password_reset_done'}, name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, {'post_reset_redirect': 'modusuario:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # register user
    url(r'^register/$', views.user_register, name='register'),

    # edit user propio
    url(r'^edit/$', views.user_detail_edit, name='edit'),

    # edit parameters
    url(r'^parameters/$', views.email_config_edit, name='configuracion'),

    # user list
    #url(r'^usuario/list/$', views.UserList.as_view(), name='listar_usuarios'),
    url(r'^usuario/list/$', views.user_list, name='listar_usuarios'),
    # user detail
    url(r'^usuario/(?P<pk>\d+)/$', views.UserDetail.as_view(), name='detalle_usuario'),
    # user create
    url(r'^usuario/create/$', views.user_create, name='crear_usuario'),
    # user update
    url(r'^usuario/(?P<pk>\d+)/update/$', views.user_update, name='actualizar_usuario'),
    # user delete
    url(r'^usuario/(?P<pk>\d+)/delete/$', views.UserDelete.as_view(), name='eliminar_usuario'),

    # area list
    url(r'^area/list/$', views.AreaList.as_view(), name='area_list'),
    # area create
    url(r'^area/create/$', views.AreaCreate.as_view(), name='area_create'),
    # area update
    url(r'^area/(?P<pk>\d+)/update/$', views.AreaUpdate.as_view(), name='area_update'),
    # area delete
    url(r'^area/(?P<pk>\d+)/delete/$', views.AreaDelete.as_view(), name='area_delete'),

    # rol list
    url(r'^rol/list/$', views.RolList.as_view(), name='rol_list'),
    # rol create
    url(r'^rol/create/$', views.RolCreate.as_view(), name='rol_create'),
    # rol update
    url(r'^rol/(?P<pk>\d+)/update/$', views.RolUpdate.as_view(), name='rol_update'),
    # rol delete
    url(r'^rol/(?P<pk>\d+)/delete/$', views.RolDelete.as_view(), name='rol_delete'),
]

modmantenimiento/models.py
from django.db import models
from modrecurso.models import TipoRecurso,Recurso
from .tasks import set_mantenimiento_as_active, set_mantenimiento_as_inactive

class Mantenimiento(models.Model):
    """
        Modelo utilizado para la creacion de mantenimientos de recursos donde se solicitan los datos necesarios para un mantenimiento
    """

    recurso = models.ForeignKey('modrecurso.Recurso', on_delete=models.CASCADE)

    fecha_hora_inicio = models.DateTimeField()
    fecha_hora_fin = models.DateTimeField(null=True, blank=True)
    motivo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)
    costo= models.FloatField(max_length=100, null=True, blank=True)
    PREVENTIVO='PREVENTIVO'
    CORRECTIVO='CORRECTIVO'
    TIPO_CHOICES = (
        (PREVENTIVO, 'Preventivo'),
        (CORRECTIVO, 'Correctivo'),
    )
    tipo = models.CharField(
        max_length=10,
        choices=TIPO_CHOICES
    )
    CONFIRMADO = 'CONFIRMADO'
    CANCELADO = 'CANCELADO'
    ESTADO_CHOICES = (
        (CONFIRMADO, 'Confirmado'),
        (CANCELADO, 'Cancelado'),
    )
    estado = models.CharField(
        max_length=10,
        choices=ESTADO_CHOICES,
        blank=True,
        null=True
    )
    DISPONIBLE = 'DISPONIBLE'
    DESCOMPUESTO = 'DESCOMPUESTO'
    INUTILIZABLE = 'INUTILIZABLE'
    RESULTADO_CHOICES = (
        (DISPONIBLE, 'Disponible'),
        (DESCOMPUESTO, 'Descompuesto'),
        (INUTILIZABLE, 'Inutilizable'),
    )
    resultado = models.CharField(
        max_length=12,
        choices=RESULTADO_CHOICES
    )


    class Meta:
        permissions = (
            ("list_all_mantenimiento", "Can list all mantenimiento"),
            ("list_mantenimiento", "Can list a certain mantenimiento"),
        )

    def __str__(self):
        return self.tipo

    def save(self, *args, **kwargs):

        create_task = False  # variable to know if celery task is to be created
        create_task2 = False
        if self.pk is None:  # Check if instance has 'pk' attribute set
            # Celery Task is to created in case of 'INSERT'
            create_task = True  # set the variable
            if self.fecha_hora_fin:
                create_task2 = True

        super(Mantenimiento, self).save(*args, **kwargs)  # Call the Django's "real" save() method.

        if create_task:  # check if task is to be created
            # pass the current instance as 'args' and call the task with 'eta' argument
            # to execute after the race `end_time`
            set_mantenimiento_as_active.apply_async(args=[self.recurso.id],
                                             eta=self.fecha_hora_inicio)  # task will be executed after 'race_end_time'

        if create_task2:
            set_mantenimiento_as_inactive.apply_async(args=[self.recurso.id],
                                                    eta=self.fecha_hora_fin)

modmantenimiento/forms.py
from django import forms
from .models import Mantenimiento
from modrecurso.models import Recurso, TipoRecurso
from modusuario.models import Area
from datetimewidget.widgets import DateTimeWidget, DateWidget, TimeWidget
from datetime import datetime, date, time, timedelta, timezone
from  django.utils import timezone
import pytz, datetime

class FormCrearMantenimientoPreventivo(forms.ModelForm):
    """
         Formulario que se utiliza para la visualizacion de mantenimientos preventivos, para el ingreso de fechas_horas se muestran widgets.
     """

    def __init__(self, *args, **kwargs):
        super(FormCrearMantenimientoPreventivo, self).__init__(*args, **kwargs)
        #self.fields['recurso'] = forms.ModelChoiceField(required=True, queryset=Recurso.objects.filter(estado=Recurso.DISPONIBLE))
        self.fields['recurso'].help_text = 'Los recursos que estan en estado ' + Recurso.DISPONIBLE

    recurso_nombre = forms.CharField(label="Recurso", widget=forms.TextInput(attrs={'readonly':'readonly'}))
    costo = forms.FloatField(min_value=0, required=True)
    fecha_hora_inicio = forms.DateTimeField(label="Fecha de Inicio", input_formats=['%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M'], widget = DateTimeWidget(usel10n=True, attrs={'id': "fecha_hora_inicio", 'class': 'input[type=date].form-control'}, bootstrap_version=2))
    fecha_hora_fin = forms.DateTimeField(label="Fecha de Fin", required=True, input_formats=['%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M'], widget = DateTimeWidget(usel10n=True, attrs={'id': "fecha_hora_fin", 'class': 'input[type=date].form-control'}, bootstrap_version=2))

    class Meta:
        model = Mantenimiento
        fields = ('recurso_nombre', 'recurso','fecha_hora_inicio', 'fecha_hora_fin', 'motivo', 'descripcion', 'costo')
        widgets = {'recurso': forms.HiddenInput(), 'descripcion': forms.Textarea}

    def clean_fecha_hora_fin(self):
        print(self.cleaned_data)
        fecha_ini = self.cleaned_data['fecha_hora_inicio']
        fecha_fin = self.cleaned_data['fecha_hora_fin']
        fecha_semana =  timezone.make_aware(datetime.datetime.now() + datetime.timedelta(days=7)) # esto funcionaba antes?
        tiempo_inicial = datetime.time(7, 15, 0, 0)
        tiempo_final = datetime.time(22, 15, 0, 0)

        #tiempo_final =  + timedelta(hours=22, minutes=15)
        if fecha_ini < fecha_semana:
            raise forms.ValidationError('La fecha inicial debe ser almenos 1 semana despues de la fecha actual')
        elif fecha_ini > fecha_fin:
            raise forms.ValidationError('La fecha inicial es mayor que la fecha final')
        elif fecha_ini.time() < tiempo_inicial or fecha_ini.time() > tiempo_final or fecha_fin.time() > tiempo_final:     # para que solo se puede crear man tenimiento en el rango de hora de 7:15 a 22:15
            raise forms.ValidationError('La hora debe ser entre 7:15 a 22:15')
        return fecha_fin

class FormCrearMantenimientoCorrectivo(forms.ModelForm):
    """
         Formulario que se utiliza para la visualizacion de mantenimientos correctivos, se tiene mensajes de ayuda y restricciones.
     """
    def __init__(self, *args, **kwargs):
        super(FormCrearMantenimientoCorrectivo, self).__init__(*args, **kwargs)
        #self.fields['recurso'] = forms.ModelChoiceField(required=True, queryset=Recurso.objects.filter(estado=Recurso.DESCOMPUESTO))
        self.fields['recurso'].help_text = 'Los recursos que estan en estado ' + Recurso.DESCOMPUESTO

    recurso_nombre = forms.CharField(label="Recurso", widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    fecha_hora_inicio = forms.DateTimeField(label="Fecha de Inicio", input_formats=['%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M'], widget=DateTimeWidget(usel10n=True, attrs={'id': "fecha_hora_inicio", 'class': 'input[type=date].form-control'}, bootstrap_version=2))

    class Meta:
        model = Mantenimiento
        fields = ('recurso_nombre', 'recurso','fecha_hora_inicio', 'motivo')
        widgets = {'recurso': forms.HiddenInput()}

    def clean_fecha_hora_inicio(self):
        fecha_ini = self.cleaned_data['fecha_hora_inicio']
        fecha_hoy = timezone.make_aware(datetime.datetime.now())
        if fecha_ini <= fecha_hoy:
            raise forms.ValidationError('La fecha inicial minima debe ser a partir de la fecha actual')
        return fecha_ini

class FormEditarMantenimientoCorrectivo(forms.ModelForm):
    """
             Formulario que se utiliza para la modificacion de mantenimientos, con ayudas y widgets.
    """

    costo = forms.FloatField(min_value=0, required=True)
    fecha_hora_fin = forms.DateTimeField(label="Fecha de Fin", required=True, input_formats=['%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M'], widget = forms.DateTimeInput(attrs={'readonly': True}))

    class Meta:
        model = Mantenimiento
        fields = ('fecha_hora_fin', 'descripcion', 'costo', 'resultado')

        widgets = {'descripcion': forms.Textarea}

        help_texts = {
            'descripcion': 'Cosas que se le realizaron al recurso',
            'resultado': 'Si el recurso sigue descompuesto o puede ser utilizado'
        }

class FormBuscarRecurso(forms.Form):
    """
        Formulario utilizado para buscar un recurso

    """

    def __init__(self, *args, **kwargs):
        super(FormBuscarRecurso, self).__init__(*args, **kwargs)
        self.fields['nombre'] = forms.CharField(required=False)
        self.fields['area'] = forms.ModelChoiceField(required=False, queryset=Area.objects.all())
        self.fields['tipo_recurso'] = forms.ModelChoiceField(required=False, queryset=TipoRecurso.objects.all())

modmantenimiento/templates/modmantenimiento/base_modmantenimiento.html
{#cambiar estado en mantenimiento#}
{#Validaciones la fecha (correctivo: matar las reservas preventivo: fecha mantenimiento min menor a una semana), el costo#}

{% extends "base.html" %}

{% block title %}Modulo de Recursos{% endblock %}

{% block dropdown-inactive %}inactive{% endblock %}

{% block dropdown-menu %}
{% endblock %}

{% block content %}
{% endblock %}

modmantenimiento/templates/modmantenimiento/buscar_recurso_lista.html
{% extends "modmantenimiento/base_modmantenimiento.html" %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1> Buscar Recurso </h1>
            <hr>
            <p>Ingresa los siguientes datos: </p><br>
            <form id="searchform" action="." method="get">
                {{ form.as_p }}
                <button type="submit" name="buscar" class="btn btn-primary">Buscar</button>
            </form>
            <table id="Table_area" class="header" cellspacing="0" width="100%">
                <thead class="table">
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Tipo Recurso</th>
                        <th>Area</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for recurso in recurso_list %}
                        <form id="submitform" action="." method="post">
                        {% csrf_token %}
                            <tr>
                                <td>{{ recurso.id }}</td>
                                <td>{{ recurso.nombre }}</td>
                                <td>{{ recurso.tipo_recurso.nombre }}</td>
                                <td>{{ recurso.area.nombre }}</td>
                                <td><button type="submit" name="seleccionar" class="btn btn-primary">Seleccionar</button></td>
                            </tr>
                            <input type="hidden" name="recurso_id" value="{{ recurso.id }}">
                        </form>
                    {% endfor %}
                </tbody>
            </table>
            {% if recurso_list.has_other_pages  %}
                <ul class="pagination">
                    {% if recurso_list.has_previous %}
                        {# No me pregunten como, pero toda esa parte del codigo a partir del "for key...." es para que no se pierdan los parametros al cambiar de pagina #}
                        <li><a href="?page={{ recurso_list.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in recurso_list.page_range %}
                        {% if recurso_list.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if recurso_list.has_next %}
                            <li><a href="?page={{ recurso_list.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&raquo;</a></li>
                    {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
            <br><br>
            <a class="btn btn-sm btn-primary" href="{% url nombre_url %}" role="button">&laquo; Atrás </a>
        </div>
    </div>
{% endblock %}

modmantenimiento/templates/modmantenimiento/crear_mantenimiento.html
{% extends "modmantenimiento/base_modmantenimiento.html" %}

{% block title %}Crear mantenimiento{% endblock %}

{% block extrahead %}
    {{ form.media }}
{% endblock %}

{% block content %}
    {% if perms.modmantenimiento.add_mantenimiento %}
        <div class="container">
            <div class="jumbotron">
                <h1> Nuevo Mantenimiento </h1>
                <hr>
                <p>Ingresa los siguientes datos: </p><br>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="modal-footer" style="text-align:left">
                        <a href="{% url 'modmantenimiento:mantenimiento_lista' %}" class="btn btn-primary" role="button">Cancelar </a>
                        <button type="submit" class="btn btn-primary">Crear</button>
                    </div>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h1> Permiso denegado! </h1><br>
                <p> Usted no posee permiso para crear recurso </p><br>
            </div>
        </div>
    {% endif %}

    <script>
    $(document).ready(function() {
        var $recurso = $("#id_recurso_nombre")
        $recurso.click(function() {
            document.location.href = "{% url 'modmantenimiento:buscar_recurso_lista' %}";
        });
        $recurso.after(" <a class='btn btn-sm btn-primary' href='{% url 'modmantenimiento:buscar_recurso_lista' %}' role='button'>Buscar</a>");
    });
</script>

{% endblock content %}

modmantenimiento/templates/modmantenimiento/eliminar_mantenimiento.html
{% extends "modmantenimiento/base_modmantenimiento.html" %}

{% block title %}Mantenimiento eliminado{% endblock %}

{% block content %}
    {% if perms.modmantenimiento.delete_mantenimiento %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Mantenimiento eliminado </h1><hr>
              <p>Su mantenimiento ha sido eliminado exitosamente. Ahora puedes <a href="{% url "modmantenimiento:mantenimiento_lista" %}">volver</a></p><br>
          </div>
        </div>
    {% else %}
        <p></p>
        <div class="container" >
          <div class="jumbotron">
              <h1> Permiso denegado! </h1><hr>
              <p>No posee permiso para eliminar mantenimiento.<br>
          </div>
        </div>
    {% endif %}
{% endblock content %}

modmantenimiento/templates/modmantenimiento/mantenimiento_creado.html
{% extends "modmantenimiento/base_modmantenimiento.html" %}

{% block title %}Mantenimiento Creado{% endblock %}

{% block content %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Mantenimiento Creado </h1><hr>
              <p>Su mantenimiento ha sido creado exitosamente. Ahora puedes <a href="{% url 'modmantenimiento:mantenimiento_lista' %}">volver</a></p><br>
          </div>
        </div>
{% endblock content %}

modmantenimiento/templates/modmantenimiento/mantenimiento_lista.html
{% extends "modmantenimiento/base_modmantenimiento.html" %}

{% load static i18n %}

{% block title %}Mantenimiento{% endblock %}

{% block content %}

    <div class="container" >
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Mantenimiento</h1><hr>
        <input type="text" id="myInput" class="form-control" onkeyup="buscar()" placeholder="Ingrese la fecha del mantenimiento que desea buscar.">
         <br>
        <table id="myTable" class="header" cellspacing="0 " width="100%">
            <thead class="table">
                <tr>
                    <th>Nombre Recurso</th>
                    <th>Motivo</th>
                    <th>Costo</th>
                    <th>Tipo</th>
                    <th>Estado</th>
                    <th>Resultado</th>
                    <th>Detalles</th>
                    <th>Modificar</th>
                    <th>Cancelar/<br>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for Mantenimiento in mantenimientos %}
                    <tr>
                        <td>{{ Mantenimiento.recurso }}</td>
                        <td>{{ Mantenimiento.motivo }}</td>
                        <td>{{ Mantenimiento.costo }}</td>
                        <td>{{ Mantenimiento.tipo }}</td>
                        <td>{{ Mantenimiento.estado }}</td>
                        <td>{{ Mantenimiento.resultado }}</td>
                        <td>
                            <img src="{% static 'img/detalles2.png' %}" width="25" height="25" alt="more" style="cursor: pointer;" data-toggle="modal" data-target="#myModal{{ forloop.counter }}">
                            <!-- Modal -->
                            <div class="modal fade" id="myModal{{ forloop.counter }}" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h3 class="modal-title"> Detalles del Mantenimiento </h3>
                                        </div>
                                        <div class="modal-body" style="text-align:left">
                                           <h3>Fecha y hora de inicio</h3>
                                           {{ Mantenimiento.fecha_hora_inicio }}
                                           <hr>
                                           <h3>Fecha y hora de fin</h3>
                                           {{ Mantenimiento.fecha_hora_fin }}
                                           <hr>
                                           <h3>Descripción</h3>
                                           {{ Mantenimiento.descripcion }}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </td>

                        <td>
                            {% if perms.modmantenimiento.change_mantenimiento and Mantenimiento.tipo == Mantenimiento.CORRECTIVO and not Mantenimiento.resultado and Mantenimiento.estado != Mantenimiento.CANCELADO %}
                                <a href="{% url "modmantenimiento:modificar_mantenimiento" parameter=Mantenimiento.id %}"><img src="{% static 'img/editar_recurso.png' %}" width="25" height="25" alt="editar1"/></a>
                            {% endif %}
                        </td>

                        {% if perms.modmantenimiento.delete_mantenimiento and Mantenimiento.estado != Mantenimiento.CANCELADO%}
                            <td><a href="{% url "modmantenimiento:eliminar_mantenimiento" parameter=Mantenimiento.id %}"><img src="{% static 'img/eliminar1.png' %}" width="25" height="25" alt="eliminar"/></a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if mantenimientos.has_other_pages %}
            <ul class="pagination">
                {% if mantenimientos.has_previous %}
                    <li><a href="?page={{ mantenimientos.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in mantenimientos.paginator.page_range %}
                    {% if mantenimientos.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if mantenimientos.has_next %}
                        <li><a href="?page={{ mantenimientos.next_page_number }}">&raquo;</a></li>
                {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
        <br><br>
            <a class="btn btn-sm btn-primary" href="{% url "modusuario:home" %}" role="button">&laquo; Atrás </a>
        &nbsp;&nbsp;
        {% if perms.modmantenimiento.add_mantenimiento %}
            <a class="btn btn-sm btn-primary" href="{% url "modmantenimiento:crear_mantenimiento_preventivo" %}" role="button">Crear Preventivo</a>&nbsp &nbsp
            <a class="btn btn-sm btn-primary" href="{% url "modmantenimiento:crear_mantenimiento_correctivo" %}" role="button">Crear Correctivo</a>&nbsp &nbsp
        {% endif %}
      </div>
    </div> <!-- /container -->

    <script>
        function buscar()
        {
            var input, filter, table, tr, td, i;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td)
                {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1)
                    {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

{% endblock content %}

modmantenimiento/templates/modmantenimiento/mantenimiento_modificado.html
{% extends "modmantenimiento/base_modmantenimiento.html" %}

{% block title %}Mantenimiento Modificado{% endblock %}

{% block content %}
        <div class="container" >
          <div class="jumbotron">
              <h1> Mantenimiento Modificado </h1><hr>
              <p>Su mantenimiento ha sido modificado exitosamente. Ahora puedes <a href="{% url "modmantenimiento:mantenimiento_lista" %}">volver</a></p><br>
          </div>
        </div>
{% endblock content %}

modmantenimiento/templates/modmantenimiento/modificar_mantenimiento.html
{% extends "modmantenimiento/base_modmantenimiento.html" %}

{% block title %}Editar Mantenimiento{% endblock %}

{% block extrahead %}
    {{ form.media }}
{% endblock %}

{% block content %}
    {% if perms.modmantenimiento.change_mantenimiento %}
        <div class="container">
            <div class="jumbotron">
                <h1> Editar el mantenimiento </h1>
                <hr>
                <p> Puede editar el mantenimiento mediante el siguiente formulario: </p><br>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <div class="modal-footer" style="text-align:left">
                      <a href="{% url 'modmantenimiento:mantenimiento_lista' %}" class="btn btn-primary" role="button">Atras </a>
                      <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h1> Permiso denegado! </h1>
                <hr>
                <p> Usted no posee permiso para modificar mantenimiento </p><br>
            </div>
        </div>
    {% endif %}
{% endblock content %}