dubium/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from modusuario import views
#from modreserva import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('modusuario.urls')),
    url(r'^recurso/', include('modrecurso.urls')),
    url(r'^mantenimiento/', include('modmantenimiento.urls')),
    url(r'^reserva/', include('modreserva.urls')),
    url(r'^publico/', include('modpublico.urls')),
]

modrecurso/urls.py
from django.conf.urls import url
from . import views

app_name = 'modrecurso'

urlpatterns = [
    url(r'^crear/$', views.crear_recurso, name='crear_recurso'),
    url(r'^modificar-(?P<parameter>\d+)/', views.modificar_recurso, name='modificar_recurso'),
    #url(r'^listar/$', views.recurso_list, name='recurso_list'),
    url(r'^eliminar-(?P<pk>\d+)/', views.RecursoDelete.as_view(), name='eliminar_recurso'),
    #url(r'^$', views.recurso_list),
    url(r'^buscar/$', views.recurso_search, name='buscar'),
    url(r'^buscar/reporte_recurso_pdf/$',views.ReporteRecursosPDF.as_view(), name='reporte_recurso_pdf'),
    #url(r'^caracteristicas-(?P<parameter>\d+)/', views.caracteristicas_list, name='caracteristicas_list'),

    # TipoRecurso urls
    # TipoRecurso list
    url(r'^tiporecurso/list/$', views.TipoRecursoList.as_view(), name='tiporecurso_list'),
    # TipoRecurso create
    url(r'^tiporecurso/create/$', views.TipoRecursoCreate.as_view(), name='tiporecurso_create'),
    # TipoRecurso update
    url(r'^tiporecurso/(?P<pk>\d+)/update/$', views.TipoRecursoUpdate.as_view(), name='tiporecurso_update'),
    # TipoRecurso delete
    url(r'^tiporecurso/(?P<pk>\d+)/delete/$', views.TipoRecursoDelete.as_view(), name='tiporecurso_delete'),
    # CaracteristicaTipoRecurso list
    url(r'^tiporecurso/(?P<pk>\d+)/caracteristica/list$', views.caracteristicas_tiporecurso_list, name='caracteristicas_tiporecurso_list'),
    # CaracteristicaTipoRecurso create
    url(r'^tiporecurso/(?P<pk>\d+)/caracteristica/create$', views.CaracteristicaTipoRecursoCreate.as_view(), name='caracteristicas_tiporecurso_create'),

    # Caracteristicas urls
    # Caracteristica create
    url(r'^(?P<pk>\d+)/caracteristica/create/$', views.CaracteristicaCreate.as_view(), name='caracteristica_create'),

    #url(r'^buscar_recurso_list/$', views.buscar_recurso_lista, name='buscar_recurso_list'),
]

modusuario/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'modusuario'

urlpatterns = [
    # previous login view
    # url(r'^login/$', views.user_login, name='login'),

    # login / logout urls
    url(r'^login/$', auth_views.login,  name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),

    # dashboard
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # dashboard
    url(r'^$', views.home, name='home'),

    # change password urls
    url(r'^password-change/$', auth_views.password_change, {'post_change_redirect': 'modusuario:password_change_done'}, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),

    # restore password urls
    url(r'^password-reset/$', auth_views.password_reset, {'post_reset_redirect': 'modusuario:password_reset_done'}, name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, {'post_reset_redirect': 'modusuario:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # register user
    url(r'^register/$', views.user_register, name='register'),

    # edit user propio
    url(r'^edit/$', views.user_detail_edit, name='edit'),

    # edit parameters
    url(r'^parameters/$', views.email_config_edit, name='configuracion'),

    # user list
    #url(r'^usuario/list/$', views.UserList.as_view(), name='listar_usuarios'),
    url(r'^usuario/list/$', views.user_list, name='listar_usuarios'),
    # user detail
    url(r'^usuario/(?P<pk>\d+)/$', views.UserDetail.as_view(), name='detalle_usuario'),
    # user create
    url(r'^usuario/create/$', views.user_create, name='crear_usuario'),
    # user update
    url(r'^usuario/(?P<pk>\d+)/update/$', views.user_update, name='actualizar_usuario'),
    # user delete
    url(r'^usuario/(?P<pk>\d+)/delete/$', views.UserDelete.as_view(), name='eliminar_usuario'),

    # area list
    url(r'^area/list/$', views.AreaList.as_view(), name='area_list'),
    # area create
    url(r'^area/create/$', views.AreaCreate.as_view(), name='area_create'),
    # area update
    url(r'^area/(?P<pk>\d+)/update/$', views.AreaUpdate.as_view(), name='area_update'),
    # area delete
    url(r'^area/(?P<pk>\d+)/delete/$', views.AreaDelete.as_view(), name='area_delete'),

    # rol list
    url(r'^rol/list/$', views.RolList.as_view(), name='rol_list'),
    # rol create
    url(r'^rol/create/$', views.RolCreate.as_view(), name='rol_create'),
    # rol update
    url(r'^rol/(?P<pk>\d+)/update/$', views.RolUpdate.as_view(), name='rol_update'),
    # rol delete
    url(r'^rol/(?P<pk>\d+)/delete/$', views.RolDelete.as_view(), name='rol_delete'),
]

modrecurso/models.py
from django.db import models
from django.contrib.auth.models import User


class Recurso(models.Model):
    """
    Modelo utilizado para la creacion de recursos de la institucion, asociado con foreignKey a los modelos `modusuario.Area` y `modreserva.Mantenimiento`
    """
    EN_USO = 'EN USO'
    DISPONIBLE = 'DISPONIBLE'
    MANTENIMIENTO = 'EN MANTENIMIENTO'
    DESCOMPUESTO = 'DESCOMPUESTO'
    RESERVADO = 'RESERVADO'
    DESCONOCIDO = 'DESCONOCIDO'
    INUTILIZABLE = 'INUTILIZABLE'
    ESTADO_CHOICES = (
        (EN_USO, 'En Uso'),
        (DISPONIBLE, 'Disponible'),
        (MANTENIMIENTO, 'En Manteminiento'),
        (DESCOMPUESTO, 'Descompuesto'),
        (RESERVADO, 'Reservado'),
        (DESCONOCIDO, 'Desconocido'),
        (INUTILIZABLE, 'Inutilizable'),#todo agregar alguna forma de que pase a este estado
    )
    nombre = models.CharField(max_length=20, unique=True)
    estado = models.CharField(max_length=16, choices=ESTADO_CHOICES, blank=True,default='DISPONIBLE')
    area = models.ForeignKey('modusuario.Area')
    tipo_recurso = models.ForeignKey('TipoRecurso', on_delete=models.CASCADE)

    # import modmantenimiento
    # mantenimiento = models.ForeignKey('modmantenimiento.Mantenimiento')

    # mantenimiento = models.ForeignKey('Mantenimiento')
    # caracteristicas = models.ForeignKey('Caracteristicas', on_delete=models.CASCADE)
    # caracteristicas= models.ManyToManyField('Caracteristicas')

    class Meta:
        permissions = (
            ("list_all_recurso", "Can list all recurso"),
            ("list_recurso", "Can list a certain recurso"),
        )

    def __str__(self):
        #return 'Recurso del tipo {}'.format(self.nombre)
        return self.nombre

    def lista_caracteristicas(self):
        """
        Metodo que retorna un queryset de todas las caracteristicas (model: `modrecurso.Caracteristica`) asociadas al recurso
        """
        recurso = Recurso.objects.get(id=self.id)
        return recurso.caracteristica_set.all()

    def lista_historial(self):
         """
         Metodo que retorna un queryset de todas las caracteristicas (model: `modrecurso.Caracteristica`) asociadas al recurso
         """
         recurso = Recurso.objects.get(id=self.id)
         return recurso.historial_set.all()




class TipoRecurso(models.Model):
    """
    Modelo utilizado para categorizar los recursos (model: `modrecurso.Recurso`) por su tipo
    """
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=2000)

    def __str__(self):
        return self.nombre

    def lista_caracteristicas(self):
        """
        Metodo que retorna un queryset de todas las caracteristicas (model: `modrecurso.CaracteristicaTipoRecurso`) asociadas al tipo de recurso
        """
        tipo_recurso = TipoRecurso.objects.get(id=self.id)
        return tipo_recurso.caracteristicatiporecurso_set.all()

    class Meta:
        permissions = (
            ("list_tiporecurso", "Can list a certain tipo recurso"),
        )

class CaracteristicaTipoRecurso(models.Model):
        """
        Modelo utilizado para agregar detalles o informacion adicional a los tipos de recurso (model: `modrecurso.TipoRecurso`)
        """
        tipo_recurso = models.ForeignKey('TipoRecurso')
        nombre = models.CharField(max_length=2000)

        def __str__(self):
            return self.nombre


# reemplazado por Area de modusuario
# class Departamento(models.Model):
#     nombre = models.CharField(max_length=100)
#     descripcion = models.CharField(max_length=100)
#     def __str__(self):
#         return self.nombre


class Caracteristica(models.Model):
    """
    Modelo utilizado para agregar detalles o informacion adicional a los recursos (model: `modrecurso.Recurso`)
    """
    recurso = models.ForeignKey('Recurso')
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=2000)

    def __str__(self):
        return self.nombre

# class Mantenimiento(models.Model):
#     fechaInicio = models.DateField(blank=False)
#     fechaFin = models.DateField(blank=False)
#     motivo = models.CharField(max_length=100)
#     descripcion = models.CharField(max_length=100)
#     costo= models.FloatField(max_length=100)
#     PREVENTIVO='PREVENTIVO'
#     CORRECTIVO='CORRECTIVO'
#     TIPO_CHOICES = (
#         (PREVENTIVO, 'Preventivo'),
#         (CORRECTIVO, 'Correctivo'),
#     )
#     tipo = models.CharField(
#         max_length=10,
#         choices=TIPO_CHOICES,
#         blank=True
#     )
#     DISPONIBLE = 'DISPONIBLE'
#     DESCOMPUESTO = 'DESCOMPUESTO'
#     RESULTADO_CHOICES = (
#         (DISPONIBLE, 'Disponible'),
#         (DESCOMPUESTO, 'Descompuesto'),
#     )
#     resultado = models.CharField(
#         max_length=12,
#         choices=RESULTADO_CHOICES,
#         blank=True
#     )
#     def __str__(self):
#         return self.tipo
#

modrecurso/forms.py
from django import forms
from .models import Recurso, Caracteristica, TipoRecurso
from modusuario.models import Area, Profile
from django.contrib.auth.models import User


class FormRecurso(forms.ModelForm):
    """
    Formulario utilizado para la creacion de un recurso (model: `modrecurso.Recurso`)
    """
    class Meta:
        model = Recurso
        fields = ('nombre', 'estado', 'area', 'tipo_recurso')

class EditarForm(forms.ModelForm):
    """
        Formulario utilizado para la edicion de un recurso (model: `modrecurso.Recurso`)
    """
    class Meta:
        model = Recurso
        fields = ('nombre','estado', 'area', 'tipo_recurso')

class CaracteristicaCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        recurso_id = kwargs.pop('recurso_id')
        super(CaracteristicaCreateForm, self).__init__(*args, **kwargs)
        try:
            self.fields['nombre'] = forms.ModelChoiceField(required=True, queryset=Recurso.objects.get(id=recurso_id).tipo_recurso.caracteristicatiporecurso_set.all())
        except:
            self.fields['nombre'] = forms.ModelChoiceField(required=True, queryset=Recurso.objects.all()[:1].get().tipo_recurso.caracteristicatiporecurso_set.all())
    class Meta:
        model = Caracteristica
        fields = ('nombre', 'descripcion')

class FormFiltrosRecurso(forms.Form):

    nombre = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(FormFiltrosRecurso, self).__init__(*args, **kwargs)
        ESTADO_CHOICES = (('', 'Todos'),) + Recurso.ESTADO_CHOICES

        self.fields['tipo_recurso'] = forms.ModelChoiceField(required=False, queryset=TipoRecurso.objects.all(),
                                                             empty_label='Todos')
        self.fields['estado'] = forms.ChoiceField(required=False, choices=ESTADO_CHOICES)
        self.fields['area'] = forms.ModelChoiceField(required=False, queryset=Area.objects.all(), empty_label='Todas')

class FormReportePdf(forms.Form):

    def __init__(self, *args, **kwargs):
        super(FormReportePdf, self).__init__(*args, **kwargs)
        ESTADO_CHOICES = (('', 'Todos'),) + Recurso.ESTADO_CHOICES


        self.fields['tipo_recurso'] = forms.ModelChoiceField(required=False, queryset=TipoRecurso.objects.all(),empty_label='Todos')
        self.fields['estado'] = forms.ChoiceField(required=False, choices=ESTADO_CHOICES)
        self.fields['area'] = forms.ModelChoiceField(required=False, queryset=Area.objects.all(), empty_label='Todas')

modrecurso/templates/modrecurso/base_modrecurso.html
{% extends "base.html" %}

{% block title %}Modulo de Recursos{% endblock %}

{% block dropdown-active %}active{% endblock %}

{% block dropdown-title %}Seccion{% endblock %}

{% block dropdown-menu %}
    <li><a href="{% url "modrecurso:buscar" %}">  Recursos </a></li>
    <li><a href="{% url "modrecurso:tiporecurso_list" %}">  Tipos de Recursos</a></li>
{% endblock %}

{% block content %}
{% endblock %}

modrecurso/templates/modrecurso/caracteristica_create.html
{% extends "modrecurso/base_modrecurso.html" %}

{% block title %}Crear Caracteristicas{% endblock %}

{% block content %}
     <div class="container" >
          <div class="jumbotron">
              <h1> Caracteristicas </h1><hr>
              <p>Ingresa los siguientes datos: </p><br>
            <form method="post" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="modal-footer" style="text-align:left">
                    <a class="btn btn-primary" href="{% url "modrecurso:buscar" %}" role="button">Cancelar </a>&nbsp;&nbsp;
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
            </form>
          </div>
     </div>
{% endblock %}

modrecurso/templates/modrecurso/crear_recurso.html
{% extends "modrecurso/base_modrecurso.html" %}

{% block title %}Crear nuevo recurso{% endblock %}

{% block content %}
    {% if perms.modrecurso.add_recurso %}
        <div class="container">
            <div class="jumbotron">
                <h1> Nuevo Recurso </h1>
                <hr>
                <p>Ingresa los siguientes datos: </p>
                <form action="" method="post">
                    {% csrf_token %}
                    <!--{{ form.as_p }}-->
                    <h3 style="line-height:10pt;">Nombre: {{ form.nombre}}</h3>
                    <h3>Estado: {{ form.estado}}</h3>
                    <h3>Area: {{ form.area}}&nbsp;&nbsp;<a href="{% url 'modusuario:area_create'%}"><img src="../../../static/img/añadir2.png" width="18" height="18" alt="crear"/></a></h3>
                    <h3>Tipo de Recurso: {{ form.tipo_recurso}}&nbsp;&nbsp;<a href="{% url 'modrecurso:tiporecurso_create'%}"><img src="../../../static/img/añadir2.png" width="18" height="18" alt="crear"/></a></h3>
                    <a class="btn btn-primary" href="{% url "modrecurso:buscar" %}" role="button">Cancelar </a>&nbsp;&nbsp;
                    <button type="submit" class="btn btn-primary">Crear</button>

                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h1> Permiso denegado! </h1><br>
                <p>  Usted no posee permiso para crear recurso. Ahora puedes <a href="{% url "modrecurso:buscar" %}">volver</a> </p><br>
            </div>
        </div>
    {% endif %}
{% endblock content %}

modrecurso/templates/modrecurso/modificar_recurso.html
{% extends "modrecurso/base_modrecurso.html" %}

{% block title %}Editar recurso{% endblock %}

{% block content %}
    {% if perms.modrecurso.change_recurso %}
        <div class="container">
            <div class="jumbotron">
                <h1> Editar el recurso </h1>
                <hr>
                <p> Puede editar el recurso mediante el siguiente formulario: </p><br>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <h>Caracteristicas: <a href="{% url 'modrecurso:caracteristica_create' pk %}"><span class="glyphicon glyphicon-plus"></span></a></h>
                    <div class="row">
                        <div class="container col-sm-4" style="background-color: white">
                            {% for caracteristica in caracteristicas %}
                                <ul>
                                    <li>{{ caracteristica.nombre }}:{{ caracteristica.descripcion }} </li>
                                </ul>
                            {% empty %}
                                <h4>El recurso no tiene caracteristicas</h4>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="modal-footer" style="text-align:left">
                            <a class="btn btn-primary" href="{% url "modrecurso:buscar" %}" role="button">&laquo; Atras </a>
                            &nbsp;&nbsp;

                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal"> Guardar</button>
                            <!-- Modal -->
                                <div class="modal fade" id="myModal" role="dialog">
                                    <div class="modal-dialog">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">

                                                    <h3 class="modal-title"> Recurso Modificado! </h3>
                                            </div>
                                            <div class="modal-body">
                                                <h4>El recurso ha sido modificado exitosamente.</h4>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-default"> Aceptar </button></a>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h1> Permiso denegado! </h1>
                <hr>
                <p> Usted no posee permiso para modificar recurso </p><br>
            </div>
        </div>
    {% endif %}
{% endblock content %}

modrecurso/templates/modrecurso/recurso_lista.html
{% extends 'modrecurso/base_modrecurso.html' %}
{% load static %}
{% block title %}Recurso{% endblock %}
{% block extrahead %}
    {{ form.media }}
    {{ form1.media }}
{% endblock %}
{% block content %}

    <div class="container" >
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Recursos</h1><hr>
        <!-- BUSCAAAR-->
        <div class="row">
            <div class="col-md-12">
                <div class="input-group" id="adv-search">
                    <input type="text" class="form-control" id="myInput" onkeyup="buscar()" placeholder="Ingrese el nombre del usuario que desea buscar">
                    <div class="input-group-btn">
                        <div class="btn-group" role="group">
                            <div class="dropdown dropdown-lg">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="height: 45px;width: 45px"><img src="{% static 'img/filtro.png' %}" width="19" height="19"></button>
                                <div class="dropdown-menu dropdown-menu-right" role="menu">
                                    <form class="form-horizontal" action="." method="get" role="form">
                                        {{ form.as_p }}
                                        <button type="submit" class="btn btn-sm btn-primary" id="btnFiltrar">Filtrar</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- BUSCAAAR-->
        <br>
        <table id="Tabla_recurso" class="header" cellspacing="0" width="100%">
            <thead class="table">
                <tr>
                    <th>Nombre</th>
                    <th>Tipo de Recurso </th>
                    <th>Estado</th>
                    <th>Área</th>
                    <!--<th>Mantenimiento</th>-->
                    <th>Características</th>
                    <th>Reportes</th>
                    {% if perms.modrecurso.change_recurso %}
                        <th>Modificar</th>
                    {% endif %}
                    {% if perms.modrecurso.delete_recurso %}
                        <th>Eliminar</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for Recurso in recursos %}
                    <tr>
                        <td>{{ Recurso.nombre }}</td>
                        <td>{{ Recurso.tipo_recurso }}</td>
                        <td>{{ Recurso.estado }}</td>
                        <td>{{ Recurso.area }}</td>
                        <td>
                            <img src="{% static 'img/info.png' %}" width="25" height="25" alt="more" style="cursor: pointer;" data-toggle="modal" data-target="#myModal{{ forloop.counter }}">
                            <!-- Modal -->
                            <div class="modal fade" id="myModal{{ forloop.counter }}" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h3 class="modal-title"> Características </h3>
                                        </div>
                                        <div class="modal-body">
                                            <table class="table table-striped" id="tblGrid">
                                                <thead id="tblHead">
                                                  <tr>
                                                    <th>Id</th>
                                                    <th>Nombre</th>
                                                    <th>Descripcion</th>
                                                  </tr>
                                                </thead>
                                                <tbody>
                                                {% for Caracteristica in Recurso.lista_caracteristicas %}
                                                    <tr>
                                                        <td class="id">{{ Caracteristica.id }}</td>
                                                        <td class="nombre">{{ Caracteristica.nombre }}</td>
                                                        <td class="descripcion">{{ Caracteristica.descripcion }}</td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </td>
                        <td>
                             <img src="{% static 'img/reporte.png' %}" width="25" height="25" alt="more" style="cursor: pointer;" data-toggle="modal" data-target="#myModal2{{ forloop.counter }}">
                            <!-- Modal -->
                            <div class="modal fade" id="myModal2{{ forloop.counter }}" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h3 class="modal-title"> Reportes </h3>
                                        </div>
                                        <div class="modal-body">
                                            <table class="table table-striped" id="tblGrid">
                                                <thead id="tblHead">
                                                  <tr>
                                                    <th>Usuario</th>
                                                    <th>Recurso</th>
                                                    <th>Reserva</th>
                                                    <th>Descripcion</th>
                                                    <th>Devuelto por</th>
                                                  </tr>
                                                </thead>
                                                <tbody>
                                                {% for Historial in Recurso.lista_historial %}
                                                    <tr>
                                                        <td class="usuario">{{ Historial.usuario }}</td>
                                                        <td class="recurso">{{ Historial.recurso.nombre }}</td>
                                                        <td class="reserva">{{ Historial.reserva }}</td>
                                                        <td class="descripcion">{{ Historial.descripcion }}</td>
                                                        <td class="usuario_dev">{{ Historial.usuario_dev }}</td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </td>
                        {% if perms.modrecurso.change_recurso %}
                            <td><a href="{% url "modrecurso:modificar_recurso" parameter=Recurso.id %}"><img src="{% static 'img/editar_recurso.png' %}" width="25" height="25" alt="editar1"/></a></td>
                        {% endif %}
                        {% if perms.modrecurso.delete_recurso %}
                            <td><a href="{% url 'modrecurso:eliminar_recurso' Recurso.id %}"><img src="{% static 'img/eliminar1.png' %}" width="25" height="25" alt="eliminar"/></a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if recursos.has_other_pages %}
            <ul class="pagination">
                {% if recursos.has_previous %}
                    <li><a href="?page={{ recursos.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in recursos.paginator.page_range %}
                    {% if recursos.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if recursos.has_next %}
                        <li><a href="?page={{ recursos.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">&raquo;</a></li>
                {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
        <br><br>
        <a class="btn btn-sm btn-primary" href="{% url "modusuario:home" %}" role="button">&laquo; Atrás </a>
        &nbsp;&nbsp;
        {% if perms.modrecurso.add_recurso %}
            <a class="btn btn-sm btn-primary" href="{% url "modrecurso:crear_recurso" %}" role="button">Crear</a>
             &nbsp;&nbsp;

            <div class="btn-group dropup" role="group">
                <div class="dropdown dropdown-lg">
                   <button  style="border-radius:4px;" type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Reporte</button>
                      <div class="dropdown-menu dropdown-menu" role="menu">
                          <form class="form-horizontal" action="{% url "modrecurso:reporte_recurso_pdf" %}" method="get" role="form">
                            {{ form1.as_p }}
                            <button type="submit" class="btn btn-sm btn-primary" id="btnGenerar">Generar PDF</button>
                         </form>
                      </div>
                </div>
            </div>
        {% endif %}
      </div>
    </div> <!-- /container -->


    <script>
    function buscar()
    {
        var input, filter, table, tr, td, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("Tabla_recurso");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td)
            {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1)
                {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

    </script>


{% endblock content %}