dubium/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from modusuario import views
#from modreserva import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('modusuario.urls')),
    url(r'^recurso/', include('modrecurso.urls')),
    url(r'^mantenimiento/', include('modmantenimiento.urls')),
    url(r'^reserva/', include('modreserva.urls')),
    url(r'^publico/', include('modpublico.urls')),
]

modpublico/urls.py
from django.conf.urls import url
from . import views
from .views import estadisticas

app_name = 'modpublico'

urlpatterns = [
    # crear mantenimiento
    # url(r'^crear_correctivo/$', views.crear_mantenimiento_correctivo, name='crear_mantenimiento_correctivo'),
    #url(r'^lista_publico/$', views.publico, name='lista_publico'),
    url(r'^lista_publico/$', estadisticas.as_view(), name='lista_publico'),
    # url(r'^modificar-(?P<parameter>\d+)/', views.modificar_mantenimiento, name='modificar_mantenimiento'),
    # # lista de mantenimientos
    # url(r'^listar/$', views.mantenimiento_list, name='mantenimiento_lista'),
    # # eliminar mantenimientos
    # url(r'^eliminar-(?P<parameter>[\w-]+).html', views.eliminar_mantenimiento, name='eliminar_mantenimiento'),
]

modrecurso/urls.py
from django.conf.urls import url
from . import views

app_name = 'modrecurso'

urlpatterns = [
    url(r'^crear/$', views.crear_recurso, name='crear_recurso'),
    url(r'^modificar-(?P<parameter>\d+)/', views.modificar_recurso, name='modificar_recurso'),
    #url(r'^listar/$', views.recurso_list, name='recurso_list'),
    url(r'^eliminar-(?P<pk>\d+)/', views.RecursoDelete.as_view(), name='eliminar_recurso'),
    #url(r'^$', views.recurso_list),
    url(r'^buscar/$', views.recurso_search, name='buscar'),
    url(r'^buscar/reporte_recurso_pdf/$',views.ReporteRecursosPDF.as_view(), name='reporte_recurso_pdf'),
    #url(r'^caracteristicas-(?P<parameter>\d+)/', views.caracteristicas_list, name='caracteristicas_list'),

    # TipoRecurso urls
    # TipoRecurso list
    url(r'^tiporecurso/list/$', views.TipoRecursoList.as_view(), name='tiporecurso_list'),
    # TipoRecurso create
    url(r'^tiporecurso/create/$', views.TipoRecursoCreate.as_view(), name='tiporecurso_create'),
    # TipoRecurso update
    url(r'^tiporecurso/(?P<pk>\d+)/update/$', views.TipoRecursoUpdate.as_view(), name='tiporecurso_update'),
    # TipoRecurso delete
    url(r'^tiporecurso/(?P<pk>\d+)/delete/$', views.TipoRecursoDelete.as_view(), name='tiporecurso_delete'),
    # CaracteristicaTipoRecurso list
    url(r'^tiporecurso/(?P<pk>\d+)/caracteristica/list$', views.caracteristicas_tiporecurso_list, name='caracteristicas_tiporecurso_list'),
    # CaracteristicaTipoRecurso create
    url(r'^tiporecurso/(?P<pk>\d+)/caracteristica/create$', views.CaracteristicaTipoRecursoCreate.as_view(), name='caracteristicas_tiporecurso_create'),

    # Caracteristicas urls
    # Caracteristica create
    url(r'^(?P<pk>\d+)/caracteristica/create/$', views.CaracteristicaCreate.as_view(), name='caracteristica_create'),

    #url(r'^buscar_recurso_list/$', views.buscar_recurso_lista, name='buscar_recurso_list'),
]

modreserva/urls.py
from django.conf.urls import url
from . import views

app_name = 'modreserva'

urlpatterns = [
    #url(r'^elegir/$', views.elegir_reserva, name='elegir_reserva'),
    # crear reserva
    url(r'^crear/$', views.crear_reserva, name='crear_reserva'),
    # lista de mantenimientos
    url(r'^listar/$', views.reserva_list, name='reserva_lista'),
    url(r'^listar/reporte_reserva_pdf/$',views.ReporteReservasPDF.as_view(), name='reporte_reserva_pdf'),
    # eliminar mantenimientos
    url(r'^eliminar-(?P<parameter>[\w-]+).html', views.eliminar_reserva, name='eliminar_reserva'),
    # url(r'^mantenimiento/$', views.mantenimiento_list),
    # crear reserva anticipada
    url(r'^crearA/$', views.crear_reserva_ant, name='crear_reserva_ant'),
    # resolver reservas anticipadas
    url(r'^resolver/$', views.reserva_list_resolver, name='reserva_list_resolver'),
    # entrega-devolucion de recursos de reservas
    url(r'^entregar-(?P<parameter>[\w-]+).html', views.entrega_recurso, name='entrega_recurso'),
    #cancelar reservas
    url(r'^cancelar-(?P<parameter>[\w-]+).html', views.cancelar_reserva, name='cancelar_reserva'),
    #vista previa de la resolucion de reservas
    #url(r'^preview/$', views.vista_previa, name='vista_previa'),
    url(r'^modificar-(?P<parameter>[\w-]+).html', views.modificar_reserva, name='modificar_reserva'),
    # crear reserva
    url(r'^crearH/$', views.crear_historial, name='crear_historial'),
    #buscar recurso
    url(r'^buscar_recurso_list/$', views.buscar_recurso_lista, name='buscar_recurso_list'),
    # editar datos de reserva
    url(r'^recuperar-(?P<parameter>[\w-]+).html', views.recuperar, name='recuperar'),
]

modusuario/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'modusuario'

urlpatterns = [
    # previous login view
    # url(r'^login/$', views.user_login, name='login'),

    # login / logout urls
    url(r'^login/$', auth_views.login,  name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),

    # dashboard
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # dashboard
    url(r'^$', views.home, name='home'),

    # change password urls
    url(r'^password-change/$', auth_views.password_change, {'post_change_redirect': 'modusuario:password_change_done'}, name='password_change'),
    url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),

    # restore password urls
    url(r'^password-reset/$', auth_views.password_reset, {'post_reset_redirect': 'modusuario:password_reset_done'}, name='password_reset'),
    url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, {'post_reset_redirect': 'modusuario:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # register user
    url(r'^register/$', views.user_register, name='register'),

    # edit user propio
    url(r'^edit/$', views.user_detail_edit, name='edit'),

    # edit parameters
    url(r'^parameters/$', views.email_config_edit, name='configuracion'),

    # user list
    #url(r'^usuario/list/$', views.UserList.as_view(), name='listar_usuarios'),
    url(r'^usuario/list/$', views.user_list, name='listar_usuarios'),
    # user detail
    url(r'^usuario/(?P<pk>\d+)/$', views.UserDetail.as_view(), name='detalle_usuario'),
    # user create
    url(r'^usuario/create/$', views.user_create, name='crear_usuario'),
    # user update
    url(r'^usuario/(?P<pk>\d+)/update/$', views.user_update, name='actualizar_usuario'),
    # user delete
    url(r'^usuario/(?P<pk>\d+)/delete/$', views.UserDelete.as_view(), name='eliminar_usuario'),

    # area list
    url(r'^area/list/$', views.AreaList.as_view(), name='area_list'),
    # area create
    url(r'^area/create/$', views.AreaCreate.as_view(), name='area_create'),
    # area update
    url(r'^area/(?P<pk>\d+)/update/$', views.AreaUpdate.as_view(), name='area_update'),
    # area delete
    url(r'^area/(?P<pk>\d+)/delete/$', views.AreaDelete.as_view(), name='area_delete'),

    # rol list
    url(r'^rol/list/$', views.RolList.as_view(), name='rol_list'),
    # rol create
    url(r'^rol/create/$', views.RolCreate.as_view(), name='rol_create'),
    # rol update
    url(r'^rol/(?P<pk>\d+)/update/$', views.RolUpdate.as_view(), name='rol_update'),
    # rol delete
    url(r'^rol/(?P<pk>\d+)/delete/$', views.RolDelete.as_view(), name='rol_delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">

        <link rel="icon" href="{% static 'img/icon.ico' %}">
        <link href="{% static 'css/bootstrap-datetimepicker.css' %}" type="text/css" media="all" rel="stylesheet" />
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
         <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
        <link href="{% static 'css/button.css' %}" rel="stylesheet">
        <link href="{% static 'css/table.css' %}" rel="stylesheet">
        <link href="{% static 'css/slide.css' %}" rel="stylesheet">
        <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>


        <style>
            canvas {
                -moz-user-select: none;
                -webkit-user-select: none;
                -ms-user-select: none;
            }
        </style>

        {% block extrahead %}{% endblock %}
        <!-- Pop up -->
    </head>
    <body>
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">DUBIUM</a>
                </div>
                {% if request.user.is_authenticated %}
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="{% block inicio-active %}{% endblock %}"><a href="{% url 'modusuario:home' %}">Inicio</a></li>
                            <li class="{% block dropdown-hide %}dropdown{% endblock %} {% block dropdown-active %}{% endblock %}">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {% block dropdown-title %}{% endblock %} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    {% block dropdown-menu %}
                                    {% endblock %}
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if perms.modusuario.can_edit_config %}
                                <li><a href="{% url "modusuario:configuracion" %}"> Configuración </a></li>
                            {% endif %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Perfil <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url "modusuario:edit" %}"><img src="{% static 'img/editar.png' %}" width="16" height="16" alt="editar"/> Editar Perfil</a></li>
                                    <li><a href="{% url "modusuario:password_change" %}"><img src="{% static 'img/pass.png' %}" width="16" height="16" alt="Pass"/> Cambiar Contraseña</a></li>
                                    {% if request.user.is_authenticated %}
                                        <li><a href="{% url "modusuario:logout" %}"><img src="{% static 'img/cerrar.png' %}" width="16" height="16" alt="Pass"/> Cerrar Sesión</a></li>
                                    {% else %}
                                        <li><a href="{% url "modusuario:login" %}"> Iniciar sesión</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </nav>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}<a href="#" class="close">✖</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>

    <!-- Bootstrap core JavaScript
       ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <script>!window.jQuery && document.write(unescape('%3Cscript src=”jquery-1.7.1.min.js”%3E%3C/script%3E'))</script>
    <script type="text/javascript" src="{% static 'js/demo.js' %}"></script>
    <script type="text/javascript" src="{% static  'js/bootstrap-datetimepicker.js' %}"></script>
   <!--  <script type="text/javascript" src="{% static 'js/Chart.bundle.js'%}"></script>-->
    <script type="text/javascript" src="{% static 'js/utils.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js'%}"></script>
    </body>
</html>

templates/inicio.html
{% extends "base.html" %}
{% load static %}
{% block title %}Inicio{% endblock %}

{% block inicio-active %}active{% endblock %}

{% block dropdown-hide %}hide{% endblock %}

{% block content %}

    <div class="container">
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
            <h1>Bienvenido {{ request.user.first_name }} !</h1>
            <hr>
            <div class="btn-group">
                {% if perms.modusuario.list_user or perms.modusuario.list_rol or perms.modusuario.list_area %}
                    <a href="{% url 'modusuario:listar_usuarios' %}"{#'admin:auth_user_changelist'#}>
                        <button class="button col-sm-2" type="submit"><br>Usuarios <br><br><br><img src="{% static 'img/usuario.png' %}" width="100" height="100" alt="usuario"></button>
                    </a>
                {% else %}
                    <button class="button6 col-sm-2" type="submit" style= "background-color:lightgrey "><br>Usuarios <br><br><br><img src="{% static 'img/usuario2.png' %}" width="100" height="100" alt="usuario"></button>
                   <!-- <button class="button col-sm-2" type="button" data-toggle="modal" data-target="#myModal" style="filter: blur(3px);"> <br>Usuarios <br><br><br><img src="{% static 'img/usuario.png' %}" width="100" height="100" alt="usuario"/></button> -->
                    <div class="modal fade" id="myModal" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title"> Permiso denegado! </h4>
                                </div>
                                <div class="modal-body">
                                    <p>Usted no tiene los permisos suficientes para ingresar al Modulo</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% if perms.modrecurso.list_recursos or perms.modrecurso.list_tiporecurso %}
                    <a href="{% url 'modrecurso:buscar' %}">
                        <button class="button col-sm-2"> <br>Recursos<br><br><br><img
                                src="{% static 'img/recurso.png' %}" width="90" height="90" alt="recurso"></button>
                    </a>
                {% else %}
                        <button class="button6 col-sm-2" style= "background-color:lightgrey "> <br>Recursos<br><br><br><img src="{% static 'img/recurso2.png' %}" width="90" height="90" alt="recurso"></button>
                {% endif %}
                <a href="{% url 'modreserva:reserva_lista' %}">
                    <button class="button col-sm-2"> <br>Reservas<br><br><br><img
                            src="{% static 'img/reservas.png' %}" width="95" height="95" alt="reservas"></button>
                </a>
                <a href="{% url 'modmantenimiento:mantenimiento_lista' %}">
                    <button class="button col-sm-2"> <br>Mantenimiento<br><br><br><img
                            src="{% static 'img/mantenimiento.png' %}" width="100" height="100" alt="mantenimiento">
                    </button>
                </a>
                <a href="{% url 'modpublico:lista_publico' %}">
                    <button class="button col-sm-2"> <br>Estadistícas<br><br><br><img src="{% static 'img/publico.png' %}"width="100" height="100"alt="publico">
                    </button>
                </a>
            </div>
        </div>
    </div>

{% endblock content %}